"""Export the WebSocket relay contract for the React client (M8 Phase 2).

The frontend has to know two things the backend owns: which event names
the relay can send, and what fields each event's payload carries. Phase 1
wrote both by hand from ``ARCHITECTURE.md``'s *illustrative* examples,
and both drifted -- eleven of fourteen event names named nothing that
existed, and three of six payload shapes had wrong field names. A handler
registered against any of them fails the same silent way: it simply never
fires, and no test notices, because both halves of the contract were
being asserted against each other's guesses.

So the contract is generated from the only authority --
``EVENT_TYPE_NAMES`` in ``core/lifecycle/runtime_ws_hub.py``, the single
map the relay dispatches through, plus the dataclass fields of each
mapped event. ``tests/unit/test_ws_contract_export.py`` asserts the
checked-in file matches what this script would write, so adding a relayed
event without regenerating fails the backend suite; ``websocket-
contract.test.ts`` asserts the TypeScript matches the file, so it fails
the frontend suite too. Neither side can drift without something going
red.

Regenerate after touching ``EVENT_TYPE_NAMES`` or any relayed event's
fields::

    python scripts/export_ws_contract.py
"""

from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import Any

from jarvis.core.lifecycle.runtime_ws_hub import EVENT_TYPE_NAMES

# Fields every ``Event`` carries. The relay lifts them out of the payload
# and onto the envelope (``envelope()`` sets ``id``/``occurred_at`` at the
# top level), so they are not payload fields from the client's side.
ENVELOPE_FIELDS: frozenset[str] = frozenset({"id", "occurred_at"})

CONTRACT_PATH = (
    Path(__file__).resolve().parents[1]
    / "frontend"
    / "src"
    / "services"
    / "websocket"
    / "event-contract.generated.json"
)


def build_contract() -> dict[str, Any]:
    """The relay's event names and payload field names, sorted."""
    events: dict[str, list[str]] = {}
    for event_type, name in EVENT_TYPE_NAMES.items():
        events[name] = sorted(
            field.name
            for field in dataclasses.fields(event_type)
            if field.name not in ENVELOPE_FIELDS
        )
    return {
        "_comment": (
            "Generated by scripts/export_ws_contract.py -- do not edit by hand. "
            "Regenerate after changing EVENT_TYPE_NAMES or any relayed event's fields."
        ),
        "transport_frames": ["heartbeat", "resume"],
        "events": dict(sorted(events.items())),
    }


def render(contract: dict[str, Any]) -> str:
    return json.dumps(contract, indent=2, sort_keys=False) + "\n"


def main() -> None:
    CONTRACT_PATH.write_text(render(build_contract()), encoding="utf-8")
    print(f"wrote {CONTRACT_PATH.relative_to(Path(__file__).resolve().parents[1])}")


if __name__ == "__main__":
    main()
