"""Browser-automation port (backed by Playwright at the infra layer)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class IBrowserAutomation(Protocol):
    """Abstract browser controller."""

    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def open(self, url: str) -> None: ...

    async def click(self, selector: str) -> None: ...

    async def type_text(self, selector: str, text: str) -> None: ...

    async def extract_text(self, selector: str) -> str: ...

    async def screenshot(self, output_path: str, *, full_page: bool = False) -> str: ...

    # --- Milestone 4 additions ------------------------------------------
    async def fill(self, selector: str, text: str) -> None: ...

    async def extract_links(self) -> list[str]: ...

    async def download(self, trigger_selector: str, output_path: str) -> str: ...

    async def close_all_tabs(self) -> int: ...
